[package]
name = "wass-rust"
version = "0.1.0"
edition = "2021"
authors = ["Cassidy"]
description = "wasm-pack rust sample"
license = "MIT/Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
